version: '3.8'

services:
  app:
    container_name: iot-platform-api
    image: iot-platform-api
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3000:3000'
