export const GLOBAL_CONFIG = {
    PORT: 'PORT',
    NODE_ENV: 'NODE_ENV',
    IS_DEVELOPMENT: 'IS_DEVELOPMENT',
    CORS_ALLOW_ORIGIN: 'CORS_ALLOW_ORIGIN',
    CONNECTION_STRING: 'CONNECTION_STRING',
    SUBSCRIPTION_ID: 'SUBSCRIPTION_ID',
    MONGO_URI: 'MONGO_URI',
};
